apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: petclinic
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/cbssjh/gitops_petclinic.git
    targetRevision: HEAD  # 기본브릿지(main 또는 master)의 최신 커맷
    path: k8s  # k8s에 있는 매니페스트 파일들이 변경되었는지 확인
  destination:
    server: https://kubernetes.default.svc
    namespace: petclinic
  syncPolicy:
    automated:   # 자동으로 클러스터의 상태를 Git 리포지토리의 상태와 동기화하려고 시도
      prune: true # Git 리포지토리에서 제거된 리소스는 Kubernetes 클러스터에서도 자동으로 삭제
      selfHeal: true # 클러스터의 리소스가 수동으로 변경되거나 삭제된 경우, ArgoCD는 이를 자동으로 감지하여 Git 리포지토리의 상태로 복원
    syncOptions: #동기화 과정에서 ArgoCD의 동작을 보다 정교하게 조정하기 위해 사용하는 옵션들
      - Validate=false #유효성 검사를 생략
      - CreateNamespace=true  # CreateNamespace=true는 지정된 네임스페이스가 존재하지 않으면 자동으로 생성
      - PrunePropagationPolicy=foreground  # 리소스가 삭제되기 전에 그 리소스에 의존하는 하위 리소스들이 먼저 삭제되도록함
      - PruneLast=true  # 동기화 과정에서 Prune 작업을 마지막에 실행하도록 지정
    retry:  #동기화가 실패했을 때 재시도를 위한 설정
      limit: 5  #동기화 실패 시 최대 5번까지 재시도
      backoff:
        duration: 5s #첫 번째 재시도까지의 대기 시간
        factor: 2 # 재시도 간의 대기 시간이 2배씩 증가
        maxDuration: 3m # 최대 대기 시간은 3분
